# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currency_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    to_rupees = [1, 82.4029, 54.8583, 104.7117, 0.5697]
    from_rupees = [1, 0.0121, 0.0182, 0.0096, 1.7559]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 390)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unit_1 = QtWidgets.QComboBox(self.centralwidget)
        self.unit_1.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.unit_1.setFont(font)
        self.unit_1.setStyleSheet("background-color: rgb(200, 213, 218)")
        self.unit_1.setEditable(False)
        self.unit_1.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.unit_1.setObjectName("unit_1")
        self.unit_1.addItem("")
        self.unit_1.addItem("")
        self.unit_1.addItem("")
        self.unit_1.addItem("")
        self.unit_1.addItem("")
        self.horizontalLayout.addWidget(self.unit_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.value_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.value_1.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.value_1.setFont(font)
        self.value_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_1.setObjectName("value_1")
        self.horizontalLayout.addWidget(self.value_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unit_2 = QtWidgets.QComboBox(self.centralwidget)
        self.unit_2.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.unit_2.setFont(font)
        self.unit_2.setStyleSheet("background-color: rgb(200, 213, 218)")
        self.unit_2.setEditable(False)
        self.unit_2.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.unit_2.setObjectName("unit_2")
        self.unit_2.addItem("")
        self.unit_2.addItem("")
        self.unit_2.addItem("")
        self.unit_2.addItem("")
        self.unit_2.addItem("")
        self.horizontalLayout_2.addWidget(self.unit_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.value_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.value_2.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.value_2.setFont(font)
        self.value_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_2.setObjectName("value_2")
        self.horizontalLayout_2.addWidget(self.value_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.value_1.setValidator(QtGui.QDoubleValidator())
        self.value_2.setValidator(QtGui.QDoubleValidator())
        self.value_1.textChanged.connect(self.convert2)
        self.value_2.textChanged.connect(self.convert1)
        self.unit_1.currentTextChanged.connect(self.convert1)
        self.unit_2.currentTextChanged.connect(self.convert2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Converter"))
        self.unit_1.setItemText(0, _translate("MainWindow", "INR"))
        self.unit_1.setItemText(1, _translate("MainWindow", "USD"))
        self.unit_1.setItemText(2, _translate("MainWindow", "AUD"))
        self.unit_1.setItemText(3, _translate("MainWindow", "GBP"))
        self.unit_1.setItemText(4, _translate("MainWindow", "JPY"))
        self.value_1.setText(_translate("MainWindow", ""))
        self.unit_2.setItemText(0, _translate("MainWindow", "INR"))
        self.unit_2.setItemText(1, _translate("MainWindow", "USD"))
        self.unit_2.setItemText(2, _translate("MainWindow", "AUD"))
        self.unit_2.setItemText(3, _translate("MainWindow", "GBP"))
        self.unit_2.setItemText(4, _translate("MainWindow", "JPY"))
        self.value_2.setText(_translate("MainWindow", ""))

    def convert1(self):
        self.value_1.textChanged.disconnect(self.convert2)
        if self.value_2.text() == "":
            self.value_1.setText("0")
        else:
            v2 = float(self.value_2.text())
            index1 = self.unit_1.currentIndex()
            index2 = self.unit_2.currentIndex()
            value = v2 * self.to_rupees[index2] * self.from_rupees[index1]
            self.value_1.setText(str(round(value, 4)))
        self.value_1.textChanged.connect(self.convert2)
    
    def convert2(self):
        self.value_2.textChanged.disconnect(self.convert1)
        if self.value_1.text() == "":
            self.value_2.setText("0")
        else:
            v1 = float(self.value_1.text())
            index1 = self.unit_1.currentIndex()
            index2 = self.unit_2.currentIndex()
            value = v1 * self.to_rupees[index1] * self.from_rupees[index2]
            self.value_2.setText(str(round(value, 4)))
        self.value_2.textChanged.connect(self.convert1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
